name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  IMAGE_NAME: byr
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  GHCR_USERNAME: ${{ github.actor }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Log in to GitHub Container Registry (GHCR)
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ env.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Extract version from pyproject.toml
      id: get_version
      run: |
        version=$(grep '^version =' pyproject.toml | cut -d '"' -f2)
        echo "VERSION=v$version" >> $GITHUB_ENV
        echo "Version: v$version"

    - name: Build and push multi-platform Docker image
      run: |
        DOCKER_IMAGE=docker.io/${DOCKERHUB_USERNAME}/$IMAGE_NAME
        GHCR_IMAGE=ghcr.io/${GHCR_USERNAME}/$IMAGE_NAME
        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          -t $DOCKER_IMAGE:$VERSION \
          -t $DOCKER_IMAGE:latest \
          -t $GHCR_IMAGE:$VERSION \
          -t $GHCR_IMAGE:latest \
          --push .
